services:
  database:
    image: postgres:17
    container_name: servbot-database
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - database.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  servbot:
    container_name: servbot
    image: ghcr.io/soaqa/servbot:latest
    env_file:
      - bot.env
    depends_on:
      database:
        condition: service_healthy
    entrypoint: "./entrypoint.sh"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable --cleanup
    restart: unless-stopped
