services:
  database:
    image: postgres:17
    container_name: servbot-database
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env_file:
      - database.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  servbot:
    container_name: servbot
    build:
      dockerfile: Dockerfile
      context: .
    image: servbot:latest
    env_file:
      - bot.env
    depends_on:
      database:
        condition: service_healthy
    entrypoint: "./entrypoint.sh"
