name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    env:
      SERVBOT_TELEGRAM_TOKEN: ${{ secrets.SERVBOT_TELEGRAM_TOKEN }}
      SERVBOT_DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
      SERVBOT_ALEMBIC_DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev-requirements.txt

      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest -vv
